### ISSUE TITLE
Header when offset

### ISSUE THREAD

**Issue by matthieumota** [doofinder/doofinder-prestashop-deprecated#41]
Why header is [not present](https://github.com/doofinder/doofinder-prestashop/blob/b0623a3cd2a09f2915fb0776a06a46e6dd5c6bb1/feed.php#L198) when offset is defined ?
In my case, there are too many products for one feed. Feed is split with limit and offset

http://url/feed.php?limit=5000&offset=0
http://url/feed.php?limit=5000&offset=5000
http://url/feed.php?limit=5000&offset=10000

When process feed on Doofinder Dashboard, it causes an error because header not present, I remove condition and it works. I can purpose on a PR or there is a good reason to keep that condition ?

**Comment by carlosescri** [comment]
Hi @matthieumota. Our modules support _pagination_. That's an internal setting of the service and we can enable it from our side. We manage the download by requesting successive _pages_ (via `limit` and `offset` parameters) and we then _glue_ the parts. That's why there's only a header in the first response, because the resulting file would end having the header repeated once per page.

Don't try to configure multiple URLs for the same feed with pagination parameters, just ask Support to enable pagination for your feed and it will work.

Hope this helps.
